### ISSUE TITLE
Variable initialization

### ISSUE THREAD

**Issue by Sieniawsky** [ericadamski/collaborative-edit#6]
Variable initialization as seen [here](https://github.com/ericadamski/collaborative-edit/blob/develop/lib/Client/client_local.coffee#L5) is not needed since CoffeeScript implicitly creates variables upon first use in code. Only structures such as empty arrays or objects should be initialized.

**Comment by ericadamski** [comment]
In most cases this is true, and I fixed these cases where I could, but there is a few non-array non-object variables that needed initialization.
