### ISSUE TITLE
Use operators provided by CoffeeScript

### ISSUE THREAD

**Issue by Sieniawsky** [ericadamski/collaborative-edit#7]
Verbose existence checks are not needed since CoffeeScript provides the `?` operator.

For instance, reference [this](https://github.com/ericadamski/collaborative-edit/blob/develop/lib/Client/client_remote.coffee#L142) code.

`return op[0].d if op[0].d isnt undefined`

can be simplified as:

`return op[0].d if op[0].d?`

or further simplified:

`return op[0].d? or 0` where 0 could be some default

**Comment by ericadamski** [comment]
I used this where I could, in some places it gave me unwanted results.
