### ISSUE TITLE
Use meaningful variable names

### ISSUE THREAD

**Issue by Sieniawsky** [ericadamski/collaborative-edit#8]
A lot of the current code base uses meaningless, or cryptic variable names, such as [here](https://github.com/ericadamski/collaborative-edit/blob/develop/lib/Client/client_remote.coffee#L127), which cause poor readability and maintainability. It's an acceptable compromise to increase readability at the expense of added verbosity.

**Comment by ericadamski** [comment]
I will let you close this one, think for the most part my variables have informative names

**Comment by Sieniawsky** [comment]
What about [this](https://github.com/ericadamski/collaborative-edit/blob/develop/lib/Client/client_remote.coffee#L111) `op` and `op[0].d` doesn't describe much.

**Comment by ericadamski** [comment]
@Sieniawsky this is part of the ShareJS API and I have no control over the poor naming of the variable `d` in `op[0].d`
